export type InstrumentConfig = {
  name: string;
  url: string;
  octaves: { [key: number]: string[] | "all" };
  notes: string[];
};

export const INSTRUMENTS: InstrumentConfig[] = [
  {
    name: "bass-electric",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/bass-electric",
    octaves: { 1: "all", 2: "all", 3: "all", 4: "all", 5: "all" },
    notes: [
      "A#1",
      "A#2",
      "A#3",
      "A#4",
      "C#1",
      "C#2",
      "C#3",
      "C#4",
      "C#5",
      "E1",
      "E2",
      "E3",
      "E4",
      "G1",
      "G2",
      "G3",
      "G4",
    ],
  },
  {
    name: "bassoon",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/bassoon",
    octaves: {
      2: ["A", "G"],
      3: ["A", "C", "G"],
      4: ["A", "C", "E", "G"],
      5: ["C"],
    },
    notes: ["A2", "A3", "A4", "C3", "C4", "C5", "E4", "G2", "G3", "G4"],
  },
  {
    name: "cello",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/cello",
    octaves: { 2: "all", 3: "all", 4: "all", 5: ["C"] },
    notes: [
      "A2",
      "A3",
      "A4",
      "A#2",
      "A#3",
      "B2",
      "B3",
      "B4",
      "C2",
      "C3",
      "C4",
      "C5",
      "C#3",
      "C#4",
      "D2",
      "D3",
      "D4",
      "D#2",
      "D#3",
      "D#4",
      "E2",
      "E3",
      "E4",
      "F2",
      "F3",
      "F4",
      "F#3",
      "F#4",
      "G2",
      "G3",
      "G4",
      "G#2",
      "G#3",
      "G#4",
    ],
  },
  {
    name: "clarinet",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/clarinet",
    octaves: {
      3: ["A#", "D", "F"],
      4: ["A#", "D", "F"],
      5: ["A#", "D", "F"],
      6: ["D", "F#"],
    },
    notes: [
      "A#3",
      "A#4",
      "A#5",
      "D3",
      "D4",
      "D5",
      "D6",
      "F3",
      "F4",
      "F5",
      "F#6",
    ],
  },
  {
    name: "contrabass",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/contrabass",
    octaves: {
      1: ["A#", "F#", "G"],
      2: ["A", "C", "C#", "D", "E", "F#", "G#"],
      3: ["B", "C#", "E", "G#"],
    },
    notes: [
      "A2",
      "A#1",
      "B3",
      "C2",
      "C#3",
      "D2",
      "E2",
      "E3",
      "F#1",
      "F#2",
      "G1",
      "G#2",
      "G#3",
    ],
  },
  {
    name: "flute",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/flute",
    octaves: {
      4: ["A", "C", "E"],
      5: ["A", "C", "E"],
      6: ["A", "C", "E"],
      7: ["C"],
    },
    notes: ["A4", "A5", "A6", "C4", "C5", "C6", "C7", "E4", "E5", "E6"],
  },
  {
    name: "piano",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/piano",
    octaves: {
      1: "all",
      2: "all",
      3: "all",
      4: "all",
      5: "all",
      6: "all",
      7: "all",
    },
    notes: [
      // Octave 1
      "C1",
      "C#1",
      "D1",
      "D#1",
      "E1",
      "F1",
      "F#1",
      "G1",
      "G#1",
      "A1",
      "A#1",
      "B1",
      // Octave 2
      "C2",
      "C#2",
      "D2",
      "D#2",
      "E2",
      "F2",
      "F#2",
      "G2",
      "G#2",
      "A2",
      "A#2",
      "B2",
      // Octave 3
      "C3",
      "C#3",
      "D3",
      "D#3",
      "E3",
      "F3",
      "F#3",
      "G3",
      "G#3",
      "A3",
      "A#3",
      "B3",
      // Octave 4
      "C4",
      "C#4",
      "D4",
      "D#4",
      "E4",
      "F4",
      "F#4",
      "G4",
      "G#4",
      "A4",
      "A#4",
      "B4",
      // Octave 5
      "C5",
      "C#5",
      "D5",
      "D#5",
      "E5",
      "F5",
      "F#5",
      "G5",
      "G#5",
      "A5",
      "A#5",
      "B5",
      // Octave 6
      "C6",
      "C#6",
      "D6",
      "D#6",
      "E6",
      "F6",
      "F#6",
      "G6",
      "G#6",
      "A6",
      "A#6",
      "B6",
      // Octave 7
      "C7",
      "C#7",
      "D7",
      "D#7",
      "E7",
      "F7",
      "F#7",
      "G7",
      "G#7",
      "A7",
      "A#7",
      "B7",
    ],
  },
  {
    name: "french-horn",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/french-horn",
    octaves: {
      1: ["A"],
      2: ["C", "D#", "G"],
      3: ["A", "D", "F"],
      4: ["C"],
      5: ["D", "F"],
    },
    notes: ["A1", "A3", "C2", "C4", "D3", "D5", "D#2", "F3", "F5", "G2"],
  },
  {
    name: "guitar-acoustic",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/guitar-acoustic",
    octaves: {
      2: "all",
      3: "all",
      4: "all",
      5: ["C", "C#", "D"],
    },
    notes: [
      "A2",
      "A3",
      "A4",
      "A#2",
      "A#3",
      "A#4",
      "B2",
      "B3",
      "B4",
      "C3",
      "C4",
      "C5",
      "C#3",
      "C#4",
      "C#5",
      "D2",
      "D3",
      "D4",
      "D5",
      "D#2",
      "D#3",
      "D#4",
      "E2",
      "E3",
      "E4",
      "F2",
      "F3",
      "F4",
      "F#2",
      "F#3",
      "F#4",
      "G2",
      "G3",
      "G4",
      "G#2",
      "G#3",
      "G#4",
    ],
  },
  {
    name: "guitar-electric",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/guitar-electric",
    octaves: {
      2: ["A", "C#", "E", "F#"],
      3: ["A", "C", "D#"],
      4: ["A", "C", "D#"],
      5: ["A", "C", "D#", "F#"],
      6: ["C"],
    },
    notes: [
      "A2",
      "A3",
      "A4",
      "A5",
      "C3",
      "C4",
      "C5",
      "C6",
      "C#2",
      "D#3",
      "D#4",
      "D#5",
      "E2",
      "F#2",
      "F#3",
      "F#4",
      "F#5",
    ],
  },
  {
    name: "guitar-nylon",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/guitar-nylon",
    octaves: {
      1: ["B", "E", "G"],
      2: ["A", "B", "D", "E", "F#", "G#"],
      3: ["A", "B", "C#", "E", "G"],
      4: ["A", "B", "C#", "D#", "F#", "G#"],
      5: ["A", "A#", "D", "E", "F#", "G", "G#"],
    },
    notes: [
      "A2",
      "A3",
      "A4",
      "A5",
      "A#5",
      "B1",
      "B2",
      "B3",
      "B4",
      "C#3",
      "C#4",
      "C#5",
      "D2",
      "D3",
      "D5",
      "D#4",
      "E2",
      "E3",
      "E4",
      "E5",
      "F#2",
      "F#3",
      "F#4",
      "F#5",
      "G3",
      "G5",
      "G#2",
      "G#4",
      "G#5",
    ],
  },
  {
    name: "harmonium",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/harmonium",
    octaves: {
      2: "all",
      3: "all",
      4: "all",
      5: ["C", "C#", "D"],
    },
    notes: [
      "A2",
      "A3",
      "A4",
      "A#2",
      "A#3",
      "A#4",
      "B2",
      "B3",
      "B4",
      "C2",
      "C3",
      "C4",
      "C5",
      "C#2",
      "C#3",
      "C#4",
      "C#5",
      "D2",
      "D3",
      "D4",
      "D5",
      "D#2",
      "D#3",
      "D#4",
      "E2",
      "E3",
      "E4",
      "F2",
      "F3",
      "F4",
      "F#2",
      "F#3",
      "G2",
      "G3",
      "G4",
      "G#2",
      "G#3",
      "G#4",
    ],
  },
  {
    name: "harp",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/harp",
    octaves: {
      1: ["B", "E", "G"],
      2: ["A", "D", "F"],
      3: ["B", "C", "E", "G"],
      4: ["A", "D", "F"],
      5: ["B", "C", "E", "G"],
      6: ["A", "B", "D", "F"],
      7: ["D", "F"],
    },
    notes: [
      "A2",
      "A4",
      "A6",
      "B1",
      "B3",
      "B5",
      "B6",
      "C3",
      "C5",
      "D2",
      "D4",
      "D6",
      "D7",
      "E1",
      "E3",
      "E5",
      "F2",
      "F4",
      "F6",
      "F7",
      "G1",
      "G3",
      "G5",
    ],
  },
  {
    name: "organ",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/organ",
    octaves: {
      1: ["A", "C", "D#", "F#"],
      2: ["A", "C", "D#", "F#"],
      3: ["A", "C", "D#", "F#"],
      4: ["A", "C", "D#", "F#"],
      5: ["A", "C", "D#", "F#"],
      6: ["C"],
    },
    notes: [
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "D#1",
      "D#2",
      "D#3",
      "D#4",
      "D#5",
      "F#1",
      "F#2",
      "F#3",
      "F#4",
      "F#5",
    ],
  },
  {
    name: "saxophone",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/saxophone",
    octaves: {
      3: "all",
      4: "all",
      5: "all",
    },
    notes: [
      "A4",
      "A5",
      "A#3",
      "A#4",
      "B3",
      "B4",
      "C4",
      "C5",
      "C#3",
      "C#4",
      "C#5",
      "D3",
      "D4",
      "D5",
      "D#3",
      "D#4",
      "D#5",
      "E3",
      "E4",
      "E5",
      "F3",
      "F4",
      "F5",
      "F#3",
      "F#4",
      "F#5",
      "G3",
      "G4",
      "G5",
      "G#3",
      "G#4",
      "G#5",
    ],
  },
  {
    name: "trombone",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/trombone",
    octaves: {
      1: ["A#"],
      2: ["A#", "C#", "D#", "F", "G#"],
      3: ["A#", "C", "D", "D#", "F"],
      4: ["C", "C#", "D", "D#", "F"],
    },
    notes: [
      "A#1",
      "A#2",
      "A#3",
      "C3",
      "C4",
      "C#2",
      "C#4",
      "D3",
      "D4",
      "D#2",
      "D#3",
      "D#4",
      "F2",
      "F3",
      "F4",
      "G#2",
      "G#3",
    ],
  },
  {
    name: "trumpet",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/trumpet",
    octaves: {
      3: ["A", "F"],
      4: ["A#", "C", "D#", "F", "G"],
      5: ["A", "D", "F"],
      6: ["C"],
    },
    notes: ["A3", "A5", "A#4", "C4", "C6", "D5", "D#4", "F3", "F4", "F5", "G4"],
  },
  {
    name: "tuba",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/tuba",
    octaves: {
      1: ["A#", "F"],
      2: ["A#", "D#", "F"],
      3: ["A#", "D", "F"],
    },
    notes: ["A#1", "A#2", "A#3", "D3", "D4", "D#2", "F1", "F2", "F3"],
  },
  {
    name: "violin",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/violin",
    octaves: {
      3: ["A", "G"],
      4: ["A", "C", "E", "G"],
      5: ["A", "C", "E", "G"],
      6: ["A", "C", "E", "G"],
      7: ["C"],
    },
    notes: [
      "A3",
      "A4",
      "A5",
      "A6",
      "C4",
      "C5",
      "C6",
      "C7",
      "E4",
      "E5",
      "E6",
      "G3",
      "G4",
      "G5",
      "G6",
    ],
  },
  {
    name: "xylophone",
    url: "https://bzdfmutmiehacjojxtaz.supabase.co/storage/v1/object/public/samples/xylophone",
    octaves: {
      4: ["G"],
      5: ["C", "G"],
      6: ["C", "G"],
      7: ["C", "G"],
      8: ["C"],
    },
    notes: ["C5", "C6", "C7", "C8", "G4", "G5", "G6", "G7"],
  },
];
